### ISSUE TITLE
Cannot reset password loop

### ISSUE THREAD

**Issue by mikeritter** [justintadlock/members#101] opened 2016-06-22 12:08 UTC
When site is locked down to logged-in users the forgot password path is inaccessible.

Solution: allow access to reset password files.

**Comment by justintadlock** [comment] 2016-06-22 17:04
The private site system only runs on the `template_redirect` hook.  That hook is never fired on the login/register/reset pages.  It's only fired on the front end of the site.  I just tested to make sure everything was working as it should be.

It sounds like you have another issue that's going on.  You are going to this page, correct? `yoursite.com/wp-login.php?action=lostpassword`

**Comment by justintadlock** [comment] 2016-10-07 19:21
Closing this because no further feedback was given and I could not reproduce the issue.

**Closed by justintadlock** 2016-10-07 19:21 UTC
Labels: invalid
