### ISSUE TITLE
Redirect to content after login

### ISSUE THREAD

**Issue by lmartins** [justintadlock/members#50] opened 2015-07-23 09:05 UTC
Would it be possible for the login widget to redirect the user to the previous page, instead of the Dashboard?

**Comment by nemchik** [comment] 2016-01-22 15:24
I've noticed this is also an issue when I set my entire site to members only. all logins redirect to the dashboard rather than the page the user tried to visit.
This would be very appreciated.

**Comment by justintadlock** [comment] 2016-01-22 21:05
@nemchik - That is a different issue than the login widget.  While I'm here though, I can say that is a WP issue, not a Members issue.  WP should redirect you back to the correct page.

**Comment by justintadlock** [comment] 2016-10-04 17:03
I'm closing this because I haven't  been able to reproduce the issue.

**Closed by justintadlock** 2016-10-04 17:03 UTC
