### ISSUE TITLE
Get User's Roles

### ISSUE THREAD

**Issue by cgidds** [justintadlock/members#165] opened 2017-10-20 19:50 UTC
Is there a way to get all roles assigned to a user? We're migrating from the Groups plugin to the Members plugin and trying to retrofit existing code to the new plugin. Thanks.

**Comment by justintadlock** [comment] 2017-10-20 19:52
@cgidds - Yes, it's possible to get all of a user's roles.  If you need help, I run support at [Theme Hybrid](https://themehybrid.com).

I'm going to close this ticket simply because it's not a bug or feature request.

**Closed by justintadlock** 2017-10-20 19:52 UTC
