### ISSUE TITLE
No Role Assigned to New User on Multisite

### ISSUE THREAD

**Issue by leclaeli** [justintadlock/members#153] opened 2017-08-22 19:54 UTC
When adding a new user to a site on a multisite install, capabilities and roles aren't being added to the user. 

In the signups table the meta value for new_role is "N" and the capabilities value in the usermeta table is empty. 

If the print_scripts method on [line 75 in the User_New class](https://github.com/justintadlock/members/blob/master/admin/class-user-new.php) is commented out everything works. However, because the print_scripts is removing the default role value WP seems to be using this to do the final role assignment.

**Comment by justintadlock** [comment] 2017-08-22 19:58
I don't use multisite.  But, if you can give me a step-by-step process on how to reproduce the issue (screenshots of what you have selected might be helpful), I'll look into it.

**Comment by leclaeli** [comment] 2017-08-22 20:46
1. Create user
![screen shot 2017-08-22 at 3 20 34 pm](https://user-images.githubusercontent.com/5065606/29586511-85d9bbf6-8750-11e7-975c-7c5396f62e3d.png)
2. User is not added to site
![screen shot 2017-08-22 at 3 20 58 pm](https://user-images.githubusercontent.com/5065606/29586513-85d9b020-8750-11e7-9371-84fcf8119e3d.png)
3. User is assigned to site and added to network
![screen shot 2017-08-22 at 3 21 21 pm](https://user-images.githubusercontent.com/5065606/29586515-85e23740-8750-11e7-97d4-34d9e80b1fdc.png)
4. wp_signups table
![screen shot 2017-08-22 at 3 30 50 pm](https://user-images.githubusercontent.com/5065606/29586514-85dbb3e8-8750-11e7-8ff0-b2f3f219c8a8.png)
5. wp_usermeta table - no capabilities
![screen shot 2017-08-22 at 3 31 37 pm](https://user-images.githubusercontent.com/5065606/29586512-85da0084-8750-11e7-9357-929affcef967.png)

**Comment by saulirajala** [comment] 2017-08-25 09:04
+1 for this. 

I have noticed that this issue occurs only if you have allowed users to be assigned more than a single role.

WordPress will create new user differently on multisite than in singlesite. You should see wp-admin/user-new.php lines 137-167 with Core version 4.8.1. I think the point of interest here is especially line 154: `wpmu_signup_user( $new_user_login, $new_user_email, array( 'add_to_blog' => $wpdb->blogid, 'new_role' => $_REQUEST['role'] ) );` 
With multiple roles allowed `$_REQUEST['role']` is empty. All the roles are in `$_REQUEST['members_user_roles']`

**Comment by justintadlock** [comment] 2017-08-25 15:30
Can I get y'all to test that last commit on the [2.0 branch](https://github.com/justintadlock/members/tree/2.0)?

**Comment by saulirajala** [comment] 2017-08-28 09:49
Thanks! Seems to work for me 👍

**Comment by leclaeli** [comment] 2017-08-29 18:24
It works except if you for some reason don't assign any role. So maybe there should be a default assigned or validate that a role has been assigned?

**Comment by justintadlock** [comment] 2017-08-29 18:33
WordPress allows for users without a role, so that really should be a non-issue.  There might be a legit reason to add a user without a role.

Unless there's an actual error with that, I'd rather not override user choice.  I could do an "Are You Sure?" popup in the case of not selecting a role.  That might be a good middle ground.

**Comment by leclaeli** [comment] 2017-08-29 18:39
At least in our multisite environment, if you add a user without a role they get added to the network, but they don't show up in the list of users within the specific site you added them to. Furthermore you can't easily add a role to the user because you can't see them and you can only add roles from within individual sites. So to fix we either have to delete the user and add them again or assign a role to them directly via the database. So maybe this is a single site vs multisite issue? Can anybody else confirm this behavior?

**Comment by justintadlock** [comment] 2017-08-29 18:42
If that's the case, we can always fall back to the default role.

I'd have to check if it's an issue with single site and adding a new user.

**Comment by newtonbe** [comment] 2017-09-01 14:04
I can confirm the behavior in my network install as well. We are encountering problems across our network with site admins not being able to add users.

**Comment by leclaeli** [comment] 2017-09-01 15:12
Thanks for the update. Glad there is a consensus.


________________________________

**Comment by justintadlock** [comment] 2017-09-01 15:37
We already know there's a problem and a fix. What we need to decide now is the final price of the fix for dealing with the user not selecting any roles.

**Comment by saulirajala** [comment] 2017-09-04 06:58
I agree with @leclaeli 

Having an user added to a site in multisite installation with no roles is not preferable and should not be allowed. WordPress doesn't allow it either in multisite installation. User can be without any role in multisite, but if he/she is assigned to any site, there should be some role involved. Otherwise we are stuck with the situation that we need either to remove the user and re-add it or do the changes straight in database as @leclaeli previously explained.

**Comment by leclaeli** [comment] 2017-09-07 19:58
@justintadlock Would requiring a role to be selected if in multisite be a good solution. It seems like the safest bet to me.

**Comment by JulienMelissas** [comment] 2017-09-19 18:26
Hi @justintadlock 👋 ! Been a while 😄 

Just wanted to report in and say we were seeing this issue as well but updating your plugin in composer to your recent 2.0 branch (`"justintadlock/members": "2.0.x-dev"`) worked great and we're no longer seeing the issue.

I'd put in a vote for the default role, personally, but I guess if you'd want to be safe you could just create a user with no role I guess.

Thanks again for the fix!

**Comment by justintadlock** [comment] 2017-09-27 20:16
So, in that last commit, I decided to give the user the default role if no roles were assigned when adding a new user.

Note that this should only happen in a multisite scenario with the multiple roles feature enabled.  It should not change anything about single-site setups, which work perfectly fine adding a new user without a role.

If I could get some feedback and testing on https://github.com/justintadlock/members/commit/9c51f6c6ffc5a49f9878441c178ff35c1a08d7b2, that'd be great.  I'm hoping to push out an official update tomorrow.

**Comment by JulienMelissas** [comment] 2017-09-27 20:48
Yo @justintadlock, just did a test by updating to your latest commit, and I'm getting these errors, which I wish were a bit more helpful:

![](https://files.slack.com/files-pri/T1ZQR55PH-F7AQ9SY0N/screen_shot_2017-09-27_at_4.38.39_pm.jpg)
(we're using bedrock, so that's why the directories look a bit weird)

It didn't let us complete a user creation. I will say I was _picking_ a role for this user, in this case, I chose subscriber and a custom role and got the same results with both. I rolled back to the previous composer version (your fix you mentioned above) and it's all working great like before.

Hope that helps? Not sure if it does though. I can't dig into this today but I might be able to more towards the end of the week.

**Comment by justintadlock** [comment] 2017-09-27 21:03
You probably should've gotten that undefined index notice in the previous version too.  I'm not really sure how to work around that because WP has this hardcoded.

Basically, that notice is saying that `$_REQUEST['role']` doesn't exist, which is purposely removed by Members.  Because that particular usage (`wp-admin/includes/user.php` - 529) is hardcoded (sends off activation email)...

Well, I might be hijack the email.  Let me look into that.

**Comment by justintadlock** [comment] 2017-09-27 21:29
OK, so the above is my latest crack at it.  That commit should remove core WP's email function (where the notice was from in the above screenshot) and replace it with an email function from Members.

**Comment by justintadlock** [comment] 2017-09-27 21:31
Scratch that last commit. I'm already seeing an issue.

**Comment by justintadlock** [comment] 2017-09-27 21:33
OK.  Now.  Just maybe.  Maybe I got it right. :)  

I really need to get a multisite setup for testing.

**Comment by justintadlock** [comment] 2017-09-28 17:12
I got a multisite set up and tested some ideas.  None of it works perfectly at this point.

------

One unintended consequence of all this that we haven't talked about is Members potentially wiping out other roles that other plugins are setting.

For example, a forum plugin may have its own selector for setting the new user's "forum role".  Because of the way I've had to go about addressing this, it's super easy to wipe out that role if my plugin runs its code last.  The last thing I want to do is stomp on another plugin, particularly when it comes to something even remotely related to permissions.

------

Unfortunately, right now, WP has too many things hardcoded and is missing some crucial hooks.  

For version 2.0.1, I think the best course of action is to simply not allow multiple role selection for new users in a multisite scenario.  That would, at the very least, address the issue in this ticket.

I'll update with a new commit soon.

**Comment by justintadlock** [comment] 2017-09-28 17:26
If I can get a confirmation that the above commit fixes the original issue in the ticket, that'd be great.  I've tested it but want to make sure.

You should see the normal WP role selection for multisite.

**Comment by JulienMelissas** [comment] 2017-09-28 19:16
@justintadlock thanks for the code release. This is working for us now, and we don't need multiple role selection when creating a new user, at least currently, so this works great. Thanks!

**Comment by justintadlock** [comment] 2017-09-28 19:18
Great! I'm going to go ahead and close this ticket as fixed.  A plugin update should be coming shortly.

We can open new tickets to further address multiple roles when adding a new user in multisite.

**Closed by justintadlock** 2017-09-28 19:18 UTC
Labels: Bug, Role Manager
