### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by rankie01** [justintadlock/members#122] opened 2017-01-06 16:00 UTC
I've installed Ultimate member to manage user registrations and profile.

I've installed members to manage user roles etc. except I cannot see the user profile pages.

**Comment by rankie01** [comment] 2017-01-06 16:11
I need to add I'm not a programmer

**Comment by justintadlock** [comment] 2017-02-09 20:40
Closing this as invalid because it is a support request and not a bug or feature.

**Closed by justintadlock** 2017-02-09 20:40 UTC
Labels: invalid
