### ISSUE TITLE
Not all capabilities are visible in the tab corresponding to a custom post type

### ISSUE THREAD

**Issue by fschroiff** [justintadlock/members#169] opened 2017-11-08 11:13 UTC
This is in the tab for my "Jobs" custom post type. 
![screen shot 2017-11-08 at 12 01 07](https://user-images.githubusercontent.com/660010/32546007-e3db6852-c47d-11e7-9024-cdba79b847b8.png)

This is visible when I select the "All" tab. 
![screen shot 2017-11-08 at 12 00 53](https://user-images.githubusercontent.com/660010/32546006-e3c25fb0-c47d-11e7-9924-053b6575f057.png)

This is how I add the caps in `register_post_type`: 

```php
      'capabilities' => [
        'edit_post'          => 'edit_job',
        'delete_post'        => 'delete_job',
        'edit_posts'         => 'edit_jobs',
        'edit_others_posts'  => 'edit_others_jobs',
        'publish_posts'      => 'publish_jobs',
        'read_private_posts' => 'read_private_jobs',
        'create_posts'       => 'create_jobs',
      ],
  ```

I'd expect all of those to appear under the "Vacatures" tab.

**Comment by justintadlock** [comment] 2017-11-08 12:58
`edit_job` is a meta capability and should not be assigned to a role.  Only primitive caps should be assigned to roles.  Therefore, Members does not grab meta caps by post type.

The reason it's even listed under the "All" tab is simply because it has been assigned to a role.

This is working as intended.

**Closed by justintadlock** 2017-11-08 12:58 UTC

**Comment by fschroiff** [comment] 2017-11-08 14:41
Thank you for your comment! Helped me gain more insight. Also made me find your blog post about this subject from 2010. 👌🏻
