### ISSUE TITLE
Question regarding Stripe integration

### ISSUE THREAD

**Issue by eaglejohn** [justintadlock/members#194] opened 2018-08-10 14:28 UTC
Is there a way to connect Members to Stripe so:
- users can renew their subscription that is linked to their post(s)
- that their post(s) will expire (set to Draft) when payment is cancelled or expired
- that their post(s) keep published as long as their subscription is active

**Comment by justintadlock** [comment] 2018-08-25 11:56
All of this requires custom code.  Closing ticket since it's not a bug or feature request.

**Closed by justintadlock** 2018-08-25 11:56 UTC
Labels: Invalid
