### ISSUE TITLE
How do I add a custom capability?

### ISSUE THREAD

**Issue by emzdesign** [justintadlock/members#81] opened 2016-01-18 14:07 UTC
Hi

I'm trying to hide the link to Visual Composer on one of my user levels, but there isn't anything in the Edit Capabilities section to let me do this, so I was going to add it as a custom capability, but it only let's me add a name for the capability and not what the capability is supposed to show/hide? I had a look at the guide provided but couldn't see anything about how to add a custom capability. Any help is much appreciated.

Thanks.

**Comment by justintadlock** [comment] 2016-05-17 23:08
Closing because this is a support question and not a bug.

**Closed by justintadlock** 2016-05-17 23:08 UTC
Labels: invalid
