### ISSUE TITLE
Wordpress Categories widget don't work in logged users

### ISSUE THREAD

**Issue by voodoolopez** [justintadlock/members#89] opened 2016-04-20 15:42 UTC
Hi! We have a problem on ourwebsite about categories.
When a registered user is logged on the website, the categories widget on sidebar and footer doesn't work.

When you are not logged, it works perfectly.
We are using also:
Peter's Login Redirect 2.9.0
Erident Custom Login and Dashboard 3.5.1
Yoat SEO 3.1.2
Yandex Metrica 1.2

website is http://www.pinkermoda.com

**Comment by justintadlock** [comment] 2016-04-20 18:45
Please use a clean version of WP with no other plugins active before reporting potential bugs.  Then, provide detailed steps on reproducing the issue.

**Comment by justintadlock** [comment] 2016-06-14 23:36
Closing because there was no further feedback.

**Closed by justintadlock** 2016-06-14 23:36 UTC
